Title:	Open py2main branch in hg repository
Stat:	open
Disp:	
Prio:	med
Cats:	
Reqtrs:	
AssdTo:	stuart

2012-12-14 15:10:00 stuart
 Will create a mercurial branch named "py2maint" for critial 
 fixes needed for the Python-2 version of JMdictDB currently 
 running at edrdg.org (Jim Breen's wwjdic/jmdict et.al. projects)
 until such time as that site can be moved to the Python-3
 "default" branch which is the main development branch.

 Note only independent changes or changes merged in from the 
 default branch should occur in this one.  This branch should
 never be merged back into "default" and will eventually be
 closed.

2012-12-14 15:24:00 stuart
 Backport rev 3be4185d90ee (2012-11-25), IS-221.
 Note that this is only the fix to python/lib/fmtxml.py and does
 not include fixes to the tests or to the IS-121 doc itself.
 See the default branch for those.

 For future reference, generated patch file with:
   hg diff -r 1109 -r 1110 python/lib/fmtxml.py >xx.patch

 Then applied:
  $ patch <xx.patch
  can't find file to patch at input line 4
  Perhaps you should have used the -p or --strip option?
  The text leading up to this was:
  --------------------------
  |diff -r c2e3adbbd834 -r 3be4185d90ee python/lib/fmtxml.py
  |--- a/python/lib/fmtxml.py	Sat Nov 24 21:00:49 2012 -0700
  |+++ b/python/lib/fmtxml.py	Sun Nov 25 12:01:11 2012 -0700
  --------------------------
  File to patch: python/lib/fmtxml.py
                 \__________________/<-----copy/pasted from 4 lines above.

  patching file python/lib/fmtxml.py
  Hunk #2 succeeded at 106 (offset 3 lines).
  Hunk #3 succeeded at 116 (offset 3 lines).
  Hunk #4 succeeded at 213 (offset 3 lines).
  Hunk #5 succeeded at 239 (offset 3 lines).
 Note that I had to manually supply the filename to patch because "hg diff"s
 output is not exactly what is expected by patch.

 Looked at porting the tests but looks like too much work to port
 right now, the test fixture has changed a lot between then and now.

2012-12-14 18:50:00 stuart
 Followed the same procedure above to backport the IS-222 fix (rev
 6d69691e6d00 2012-12-14) to files:
  python/lib/jdb.py
  python/tests/data/jelparse/restr.txt
  python/tests/test_jdb_jstr_classify.py
  python/tests/test_jelparse.py
 Was unable to apply the test_jdb_jstr_classify.py patch, it was rejected
 for reasons I don't understand.  (Possibly patch has problems with utf-8
 text?)  Applied by hand.  All tests pass except for the usual failures in
 test_jelparse due to changes in the jmdict database between then and now.
 (But note there are no tests for IS-121 in previous note.)

2012-12-14 21:02:00 stuart
 Did a "make loadall".  Run correctly with Python-2 , result ok except...
 Compared data/jmdict.pgi with same file generated from same jmdict.xml
 file but with the tip of development branch with Python-3 and found a 
 number of discrepencies in the xresolv table data of the form:
  py2maint:
    13456	1	3	1	ライター・ルポルタージュ	\N	\N	\N	\N
  default:
    13456	1	3	1	ルポルタージュ・ライター	\N	\N	\N	\N
 Entry 13456 is jmdict eq# 1144190.
 The not-yet-resolved xref has the dotted pair reversed.  The python-3
 data (default branch) is correct and the swapped Python-2 xrefs result
 in the xrefs being unresolvable later.  


